apiVersion: v1
kind: Pod
metadata:
  name: k8s-app
  labels:
    app: k8s-app
spec:
  containers:
    - name: k8s-app
      image: drspacemanphd/k8s-app
      ports:
        - name: k8s-app-port
          containerPort: 8080