apiVersion: v1
kind: ReplicationController
metadata:
  name: api-replication-controller
spec:
  replicas: 2
  selector:
    app: k8s-app
  template:
    metadata:
      name: k8s-app
      labels:
        app: k8s-app
    spec:
      containers:
        - name: k8s-app
          image: drspacemanphd/k8s-app
          ports:
            - name: k8s-app-port
              containerPort: 8080